enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Disable Shorts on startup' 'Disable auto captions' 'Disable player popup panels' 'External downloads' 'Hide ads' 'Hide album cards' 'Hide autoplay button' 'Hide breaking news shelf' 'Hide endscreen cards' 'Hide info cards' 'Hide video action buttons' 'Minimized playback' 'Old video quality menu' 'Open links externally' 'Remember video quality' 'Seekbar tapping' 'SponsorBlock' 'Swipe controls' 'Video ads'"
exclusive-patches = true
version = "auto"

[Music]
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
included-patches = "'Background play' 'Minimized playback music' 'Music video ads' 'Exclusive audio playback' 'Hide get premium' 'Remove upgrade button'"
exclusive-patches = true
